# Don't print a new line at the start of the prompt
add_newline = false
scan_timeout = 50
command_timeout = 1000

[battery]
disabled = true

[time]
disabled = true

[nix_shell]
disabled = true

[username]
disabled = false

[dotnet]
disabled = true

[erlang]
symbol = "erl "

[nodejs]
symbol = "[⬢](bold green) "
